sudo: false
# Must set language to python so we can install custom python pacakges in
# docker-based travis builds
language: python
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - openssl aes-256-cbc -K $encrypted_2d2605536f57_key -iv $encrypted_2d2605536f57_iv -in android/google-api-key.json.enc -out android/google-api-key.json -d
install: pip install -r requirements.txt
script:
 - ./android/publish_apk.py
